version: '3.8'

services:
  backend:
    build:
      context: ./backend  # Path to backend Dockerfile
    container_name: fastapi_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/code  # Sync code for live changes
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend  # Path to frontend Dockerfile
    container_name: vue_frontend
    ports:
      - "8080:8080"  # Maps Nginx's port 80 to 8080 on the host machine
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
